spring.application.name=time-limiter


resilience4j.timelimiter.instances.weatherForecastLimiter.timeout-duration=2s
resilience4j.timelimiter.instances.weatherForecastLimiter.cancel-running-future=true